name: Cron Trigger Example

on:
  schedule:
    - cron: '* * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Workflow
        run: |
          echo "Running Workflow every 1 minute"
