name: Cron Trigger Example

# on:
#   schedule:
#     - cron: '* * * * *'
on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Workflow
        run: |
          echo "Running Workflow every 1 minute"
