name: Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

      environment-type:
        description: 'Environment type'
        type: choice
        required: true
        default: 'dev'
        options:
        - dev
        - prod
      
      linters: 
        description: 'Linters to run'
        type: boolean
        required: true
        default: true
        
      formatter:
        description: 'Formatter to run'
        type: boolean
        required: true
        default: false
      

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run linters
        if: inputs.linters
        run: |
          echo "Running linters"

      - name: Run formatter
        if: inputs.formatter
        run: |  
          echo "Running formatter"

  dev-deploy:
    if: inputs.environment-type == 'dev'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        run: |
          echo "Deploying to dev"

  prod-deploy:
    if: inputs.environment-type == 'prod'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        run: |
          echo "Deploying to prod"
